-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-29 02:07:21 EET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE d_account (
    id         SERIAL NOT NULL,
    account_id INTEGER NOT NULL,
    frequency  VARCHAR(30)
);

ALTER TABLE d_account ADD CONSTRAINT d_account_pk PRIMARY KEY ( id );

CREATE TABLE d_client (
    id           SERIAL NOT NULL,
    client_id    INTEGER NOT NULL,
    birth_number INTEGER
);

ALTER TABLE d_client ADD CONSTRAINT d_client_pk PRIMARY KEY ( id );

CREATE TABLE d_credit_card (
    id      SERIAL NOT NULL,
    card_id INTEGER NOT NULL,
    type    VARCHAR(10)
);

ALTER TABLE d_credit_card ADD CONSTRAINT d_credit_card_pk PRIMARY KEY ( id );

CREATE TABLE d_date (
    id    SERIAL NOT NULL,
    year  INTEGER,
    month SMALLINT,
    day   SMALLINT
);

ALTER TABLE d_date ADD CONSTRAINT d_date_pk PRIMARY KEY ( id );

CREATE TABLE d_demographic (
    id                                 SERIAL NOT NULL,
    district_id                        INTEGER NOT NULL,
    district_name                      VARCHAR(50),
    region                             VARCHAR(50),
    inhabitants                        INTEGER,
    municip_inhabitants_0_499          INTEGER,
    municip_inhabitants_500_1999       INTEGER,
    municip_inhabitants_2000_9999      INTEGER,
    municip_inhabitants_10000_inf      INTEGER,
    cities                             INTEGER,
    urban_inhabitants_ratio            FLOAT,
    avg_salary                         INTEGER,
    unemployment_rate_95               FLOAT,
    unemployment_rate_96               FLOAT, 
--  ERROR: Column name length exceeds maximum allowed length(30) 
    enterpreneurs_per_1000_inhabitants INTEGER,
    commited_crimes_95                 INTEGER,
    commited_crimes_96                 INTEGER
);

ALTER TABLE d_demographic ADD CONSTRAINT d_demographic_pk PRIMARY KEY ( id );

CREATE TABLE d_disposition (
    id      SERIAL NOT NULL,
    disp_id INTEGER NOT NULL,
    type    VARCHAR(10)
);

ALTER TABLE d_disposition ADD CONSTRAINT d_disposition_pk PRIMARY KEY ( id );

CREATE TABLE d_loan (
    id       SERIAL NOT NULL,
    loan_id  INTEGER NOT NULL,
    duration INTEGER,
    status   VARCHAR(1)
);

ALTER TABLE d_loan ADD CONSTRAINT d_loan_pk PRIMARY KEY ( id );

CREATE TABLE d_permanent_order (
    id       SERIAL NOT NULL,
    order_id INTEGER NOT NULL,
    k_symbol VARCHAR(20),
    bank     VARCHAR(2),
    account  INTEGER
);

ALTER TABLE d_permanent_order ADD CONSTRAINT d_permanent_order_pk PRIMARY KEY ( id );

CREATE TABLE d_time (
    id     SERIAL NOT NULL,
    hour   SMALLINT,
    minute SMALLINT
);

ALTER TABLE d_time ADD CONSTRAINT d_time_pk PRIMARY KEY ( id );

CREATE TABLE d_transaction (
    id        SERIAL NOT NULL,
    trans_id  INTEGER NOT NULL,
    k_symbol  VARCHAR(20),
    bank      VARCHAR(2),
    account   INTEGER,
    type      VARCHAR(10),
    operation VARCHAR(30)
);

ALTER TABLE d_transaction ADD CONSTRAINT d_transaction_pk PRIMARY KEY ( id );

CREATE TABLE f_account (
    account_id     INTEGER NOT NULL,
    client_id      INTEGER NOT NULL,
    demographic_id INTEGER NOT NULL,
    disposition_id INTEGER NOT NULL,
    "date"         INTEGER NOT NULL
);

ALTER TABLE f_account
    ADD CONSTRAINT f_account_pk PRIMARY KEY ( account_id,
                                              client_id,
                                              demographic_id,
                                              "date",
                                              disposition_id );

CREATE TABLE f_client (
    demographic_id INTEGER NOT NULL,
    client_id      INTEGER NOT NULL
);

ALTER TABLE f_client ADD CONSTRAINT f_client_pk PRIMARY KEY ( demographic_id,
                                                              client_id );

CREATE TABLE f_credit_card (
    card_id     INTEGER NOT NULL,
    account_id  INTEGER NOT NULL,
    client_id   INTEGER NOT NULL,
    issued_date INTEGER NOT NULL,
    issued_time INTEGER NOT NULL
);

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_pk PRIMARY KEY ( card_id,
                                                  account_id,
                                                  client_id,
                                                  issued_date,
                                                  issued_time );

CREATE TABLE f_loan (
    account_id INTEGER NOT NULL,
    loan_id    INTEGER NOT NULL,
    "date"     INTEGER NOT NULL,
    amount     INTEGER,
    payments   DECIMAL
);

ALTER TABLE f_loan
    ADD CONSTRAINT f_loan_pk PRIMARY KEY ( account_id,
                                           loan_id,
                                           "date" );

CREATE TABLE f_permanent_order (
    account_id INTEGER NOT NULL,
    order_id   INTEGER NOT NULL,
    amount     DECIMAL
);

ALTER TABLE f_permanent_order ADD CONSTRAINT f_permanent_order_pk PRIMARY KEY ( account_id,
                                                                                order_id );

CREATE TABLE f_transaction (
    transaction_id INTEGER NOT NULL,
    account_id     INTEGER NOT NULL,
    "date"         INTEGER NOT NULL,
    amount         DECIMAL,
    balance        DECIMAL
);

ALTER TABLE f_transaction
    ADD CONSTRAINT f_transaction_pk PRIMARY KEY ( transaction_id,
                                                  account_id,
                                                  "date" );

ALTER TABLE f_account
    ADD CONSTRAINT f_account_d_account_fk FOREIGN KEY ( account_id )
        REFERENCES d_account ( id )
            ON DELETE CASCADE;

ALTER TABLE f_account
    ADD CONSTRAINT f_account_d_client_fk FOREIGN KEY ( client_id )
        REFERENCES d_client ( id )
            ON DELETE CASCADE;

ALTER TABLE f_account
    ADD CONSTRAINT f_account_d_date_fk FOREIGN KEY ( "date" )
        REFERENCES d_date ( id )
            ON DELETE CASCADE;

ALTER TABLE f_account
    ADD CONSTRAINT f_account_d_demographic_fk FOREIGN KEY ( demographic_id )
        REFERENCES d_demographic ( id )
            ON DELETE CASCADE;

ALTER TABLE f_account
    ADD CONSTRAINT f_account_d_disposition_fk FOREIGN KEY ( disposition_id )
        REFERENCES d_disposition ( id )
            ON DELETE CASCADE;

ALTER TABLE f_client
    ADD CONSTRAINT f_client_d_client_fk FOREIGN KEY ( client_id )
        REFERENCES d_client ( id )
            ON DELETE CASCADE;

ALTER TABLE f_client
    ADD CONSTRAINT f_client_d_demographic_fk FOREIGN KEY ( demographic_id )
        REFERENCES d_demographic ( id )
            ON DELETE CASCADE;

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_d_account_fk FOREIGN KEY ( account_id )
        REFERENCES d_account ( id )
            ON DELETE CASCADE;

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_d_client_fk FOREIGN KEY ( client_id )
        REFERENCES d_client ( id )
            ON DELETE CASCADE;

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_d_credit_card_fk FOREIGN KEY ( card_id )
        REFERENCES d_credit_card ( id )
            ON DELETE CASCADE;

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_d_date_fk FOREIGN KEY ( issued_date )
        REFERENCES d_date ( id )
            ON DELETE CASCADE;

ALTER TABLE f_credit_card
    ADD CONSTRAINT f_credit_card_d_time_fk FOREIGN KEY ( issued_time )
        REFERENCES d_time ( id )
            ON DELETE CASCADE;

ALTER TABLE f_loan
    ADD CONSTRAINT f_loan_d_account_fk FOREIGN KEY ( account_id )
        REFERENCES d_account ( id )
            ON DELETE CASCADE;

ALTER TABLE f_loan
    ADD CONSTRAINT f_loan_d_date_fk FOREIGN KEY ( "date" )
        REFERENCES d_date ( id )
            ON DELETE CASCADE;

ALTER TABLE f_loan
    ADD CONSTRAINT f_loan_d_loan_fk FOREIGN KEY ( loan_id )
        REFERENCES d_loan ( id )
            ON DELETE CASCADE;

ALTER TABLE f_permanent_order
    ADD CONSTRAINT f_permanent_order_d_account_fk FOREIGN KEY ( account_id )
        REFERENCES d_account ( id )
            ON DELETE CASCADE;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE f_permanent_order
    ADD CONSTRAINT f_permanent_order_d_permanent_order_fk FOREIGN KEY ( order_id )
        REFERENCES d_permanent_order ( id )
            ON DELETE CASCADE;

ALTER TABLE f_transaction
    ADD CONSTRAINT f_transaction_d_account_fk FOREIGN KEY ( account_id )
        REFERENCES d_account ( id )
            ON DELETE CASCADE;

ALTER TABLE f_transaction
    ADD CONSTRAINT f_transaction_d_date_fk FOREIGN KEY ( "date" )
        REFERENCES d_date ( id )
            ON DELETE CASCADE;

ALTER TABLE f_transaction
    ADD CONSTRAINT f_transaction_d_transaction_fk FOREIGN KEY ( transaction_id )
        REFERENCES d_transaction ( id )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
